### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by harshithpabbati** [HarshKhandeparkar/image-sequencer-ui#1]
Try deploying this to [Netlify](https://www.netlify.com/). It's very easy to deploy. Continuous integration is also included in it.

**Comment by harshithpabbati** [comment]
@HarshKhandeparkar check this out ;)

**Comment by HarshKhandeparkar** [comment]
Hi Harshith. Let's deploy this on GitHub itself but only when we get everything organized and add some content too.

**Comment by HarshKhandeparkar** [comment]
So I'll add you as a maintainer but you cannot commit directly to the master branch, neither can I. Let's make everyone maintainers and only open PRs so that it gets reviewed by others before it gets merged. Is this ok?

**Comment by harshithpabbati** [comment]
Yeah sure :). 

> Hi Harshith. Let's deploy this on GitHub itself but only when we get everything organized and add some content too.

What should I add ?

**Comment by HarshKhandeparkar** [comment]
Whatever you want. You can start with an image component for the step images. BTW, this uses materialize.
